site:
  title: Applied Alchemy
  url: https://www.startupctobook.com
  start_page: ROOT::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui

asciidoc:
  attributes:
    page-toclevels: 2

output:
  dir: build/site
